version: '3'

services:
    web:
        image: nginx:1.10
        ports:
            - "8080:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/app
        networks:
            - dev-network
        depends_on:
            - php
    php:
        environment:
          - SYMFONY_ENV=dev
          - SYMFONY_DEBUG=1
          - DB_HOST=db
          - DB_USER=root
          - DB_PASS=q1w2e3r4
          - DB_NAME=app
          - MAILER_HOST=mailer
          - MAILER_PORT=1025
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - ./:/var/app
        networks:
            - dev-network
        depends_on:
            - db
    db:
        environment:
            MYSQL_ROOT_PASSWORD: q1w2e3r4
            MYSQL_DATABASE: app
        image: percona:5.6
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - dev-network
    mailer:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
        networks:
            - dev-network

volumes:
    db_data:

networks:
    dev-network:
        driver: bridge
