version: '3'

services:
    web:
        image: nginx:1.10
        ports:
            - "8080:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        networks:
            - dev-network
        depends_on:
            - php
    php:
        environment:
          - SYMFONY_ENV=dev
          - SYMFONY_DEBUG=1
          - DB_HOST=db
          - DB_USER=root
          - DB_PASS=q1w2e3r4
          - DB_NAME=app
        image: softbinator/sf2:0.2
        #build:
        #    context: .
        #    dockerfile: ./.docker/php/Dockerfile
        volumes:
            - ./:/var/www
        networks:
            - dev-network
        depends_on:
            - db
    db:
        environment:
            MYSQL_ROOT_PASSWORD: q1w2e3r4
            MYSQL_DATABASE: app
        image: percona:5.6
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - dev-network

volumes:
    db_data:

networks:
    dev-network:
        driver: bridge
